module.exports = {
  "react/prop-types": 0,
  "react/no-children-prop": 0,
  "class-methods-use-this": 0,
  camelcase: 0,
  "func-names": 0,
  "function-paren-newline": 0,
  "generator-star-spacing": [2, { before: true, after: true }],
  "max-classes-per-file": 0,
  "new-cap": [
    1,
    {
      newIsCap: true,
      capIsNew: false,
    },
  ],
  "no-shadow": 0,
  "no-bitwise": 0,
  "no-continue": 0,
  "no-plusplus": 0,
  "no-minusminus": 0,
  "no-underscore-dangle": 0,
  "no-await-in-loop": 0,
  "no-restricted-syntax": ["error", "WithStatement"],
  "no-case-declarations": 0,
  "no-param-reassign": 0,
  "no-use-before-define": [
    "error",
    { functions: false, classes: true, variables: true },
  ],
  "prefer-destructuring": 0,
  "prefer-object-spread": 0,
  "import/prefer-default-export": 0,
  "import/no-extraneous-dependencies": 0,
  "import/extensions": [
    "error",
    "ignorePackages",
    {
      js: "never",
      jsx: "never",
      ts: "never",
      tsx: "never",
    },
  ],
};
